import { chromium } from 'playwright';
import { routeFonts } from './fontroute.mjs';
import { memApi } from './memapi.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 810 }, ignoreHTTPSErrors: true });
await routeFonts(ctx, process.cwd() + '/fonts'); await memApi(ctx);
await ctx.addInitScript(() => { try { localStorage.setItem('claire-review.tour-seen', '1'); } catch {} });
const p = await ctx.newPage();
p.on('pageerror', e => console.log('ERR', e.message));
let n = 0; const shot = async (name) => { await p.waitForTimeout(500); await p.screenshot({ path: `probe/${String(n++).padStart(2,'0')}-${name}.jpg`, type: 'jpeg', quality: 70 }); };
await p.goto('http://localhost:5173/cases/RC-2026-1192', { waitUntil: 'networkidle' }); await p.waitForTimeout(1500);
await shot('start');
await p.keyboard.press('f'); await shot('fullnotes');
await p.getByRole('button', { name: /^Service/ }).click(); await shot('svc');
const row = p.locator('tr', { hasText: 'Placed on continuous pulse oximetry' }).first();
await row.locator('td').nth(4).hover(); await shot('hover');
await row.getByRole('button', { name: 'Change evidence' }).click(); await shot('rebind');
console.log(await p.evaluate(() => document.body.innerText.match(/.{0,80}(Select|Use|Move).{0,80}/g)?.slice(0,5)));
await b.close();
