import { chromium } from 'playwright';
import fs from 'fs';
import { routeFonts } from './fontroute.mjs';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1920, height: 1080 } });
await routeFonts(ctx, process.cwd() + '/fonts');
const p = await ctx.newPage();
await p.addInitScript(`window.META=${fs.readFileSync('meta.json', 'utf8')}`);
await p.addInitScript(`window.TIMING=${fs.readFileSync('timing.json', 'utf8')}`);
await p.goto('file://' + process.cwd() + '/comp.html');
await p.evaluate(() => window.ready());
await p.evaluate(async () => { window.render(21.8); await window._dec; document.getElementById('cursor').style.opacity = 0; });
await p.screenshot({ path: '../details-screen.jpg', type: 'jpeg', quality: 92 });
await b.close();
